### ISSUE TITLE
Memory allocation issue on amazon linux EC2

### ISSUE THREAD

**Issue by ruiponte1990** [AugustDev/nf-shard#18]
Hello,

I'm trying to get this set up on an EC2 and I'm running into a memory issue trying to build the docker with docker compose up -d nextjs.

36.70 <--- JS stacktrace --->
36.70
36.70 FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
36.75  1: 0xb83f50 node::Abort() [/usr/local/bin/node]
36.75  2: 0xa94834  [/usr/local/bin/node]
36.75  3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
36.75  4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
36.75  5: 0xf42265  [/usr/local/bin/node]
36.75  6: 0xf5474d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
36.75  7: 0xf2ee4e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]       
36.75  8: 0xf30217 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]      
36.75  9: 0xf113ea v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
36.76 10: 0x12d674f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
36.78 11: 0x17035b9  [/usr/local/bin/node]
440.3 Aborted (core dumped)
440.3 error Command failed with exit code 134.
440.4 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn build]: exit code: 134

Have you been able to run this on an EC2?

**Comment by ruiponte1990** [comment]
Hello,

I was able to get around the memory issues by switching to a larger instance but it's now crashing my nextflow workflow. When I try to run my workflow I now get an error message: "Unexpected response for request http://localhost:3000/api/trace/mYRqb0Hh-27SHrPC/begin". I have this set up to send to AWS Batch so maybe that is the issue? Have you tested this running on AWS?

**Comment by gluonfield** [comment]
Hi I have updated the docs on launching the project. I can try launching it on EC2 as well and investigate any caveats. I had successfully deployed the server on AWS Amplify and happy to share instructions if you'd like, however I host database outside AWS.

**Comment by ruiponte1990** [comment]
Okay thanks. We are investigating using this to monitor our pipelines which will be launched from an EC2 onto AWS Batch and it didn't seem to work.

**Comment by ruiponte1990** [comment]
I am trying to create a new workspace and I am getting an error from the application:

Application error: a client-side exception has occurred (see the browser console for more information).

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
596-842e3b29e6a45c05.js:1 TypeError: t.map is not a function
    at d (page-5f808178a756181f.js:1:5068)
    at ri (fd9d1056-d3e36ad29bb6d13a.js:9:38931)
    at lp (fd9d1056-d3e36ad29bb6d13a.js:9:54222)
    at im (fd9d1056-d3e36ad29bb6d13a.js:9:112592)
    at oM (fd9d1056-d3e36ad29bb6d13a.js:9:90039)
    at fd9d1056-d3e36ad29bb6d13a.js:9:89861
    at oT (fd9d1056-d3e36ad29bb6d13a.js:9:89868)
    at ov (fd9d1056-d3e36ad29bb6d13a.js:9:87506)
    at oy (fd9d1056-d3e36ad29bb6d13a.js:9:86944)
    at MessagePort.M (596-842e3b29e6a45c05.js:25:1665)

**Comment by ruiponte1990** [comment]
**It still has the same error when I run the workflow:**

$ nextflow run main.nf -params-file params.yml
N E X T F L O W  ~  version 23.04.2
Launching `main.nf` [backstabbing_heyrovsky] DSL2 - revision: b7f6c1cd38        
[-        ] process > copySampleSheetToS3       -
[-        ] process > copyAndRegisterSampleToS3 -
Unexpected response for request http://localhost:3000/api/trace/kz6k4ty_jnSL0ITa/begin

**From the terminal running the docker:**

nf-shard-nextjs-1  | - error PrismaClientInitializationError: 
nf-shard-nextjs-1  | Invalid `prisma.workflow.findMany()` invocation:
nf-shard-nextjs-1  | 
nf-shard-nextjs-1  | 
nf-shard-nextjs-1  | Can't reach database server at `localhost`:`5432`

**I can see that postgres is running on 5432 as expected:**

$ netstat -ano | grep 5432
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      
off (0.00/0/0)
tcp6       0      0 :::5432                 :::*                    LISTEN      
off (0.00/0/0)

**Comment by ruiponte1990** [comment]
Let me know if you are able to get this working with the server and database both on an EC2!

**Comment by gluonfield** [comment]
Hi @ruiponte1990 I will try today and share the instructions.

**Comment by gluonfield** [comment]
Hi @ruiponte1990 can you try running on AWS EC2 again by pulling latest code? I have optimised container image and tried running it on AWS EC2 successfully. I have also made video of how to make deploy for free using [Neon PostgreSQL and Vercel](https://github.com/AugustDev/nf-shard#method-3---vercel)

**Comment by gluonfield** [comment]
Closing the issue as it hasn't discussed for a while.
